import { NgModule } from "@angular/core";
import {
	MatAutocompleteModule,
	MatButtonModule,
	MatCardModule,
	MatChipsModule,
	MatDialogModule,
	MatExpansionModule,
	MatGridListModule,
	MatIconModule,
	MatInputModule,
	MatListModule,
	MatMenuModule,
	MatOptionModule,
	MatProgressSpinnerModule,
	MatProgressBarModule,
	MatSelectModule,
	MatSidenavModule,
	MatSnackBarModule,
	MatTableModule,
	MatTabsModule,
	MatToolbarModule,
	MatTooltipModule,
	MatCheckboxModule
} from "@angular/material";
import { FlexLayoutModule } from "@angular/flex-layout";

@NgModule({
	imports: [
		MatToolbarModule,
		MatCardModule,
		MatButtonModule,
		MatTooltipModule,
		MatExpansionModule,
		MatIconModule,
		MatInputModule,
		MatSelectModule,
		MatAutocompleteModule,
		MatTableModule,
		MatTabsModule,
		MatMenuModule,
		MatChipsModule,
		MatListModule,
		MatSidenavModule,
		MatOptionModule,
		MatSnackBarModule,
		MatGridListModule,
		MatDialogModule,
		MatProgressSpinnerModule,
		MatProgressBarModule,
		MatCheckboxModule,
		FlexLayoutModule
	],
	exports: [
		MatToolbarModule,
		MatCardModule,
		MatButtonModule,
		MatTooltipModule,
		MatExpansionModule,
		MatIconModule,
		MatInputModule,
		MatSelectModule,
		MatAutocompleteModule,
		MatTableModule,
		MatTabsModule,
		MatMenuModule,
		MatChipsModule,
		MatListModule,
		MatSidenavModule,
		MatOptionModule,
		MatSnackBarModule,
		MatGridListModule,
		MatDialogModule,
		MatProgressSpinnerModule,
		MatProgressBarModule,
		MatCheckboxModule,
		FlexLayoutModule
	]
})
export class MaterialModule {}
